### ISSUE TITLE
instructions out of date.

### ISSUE THREAD

**Issue by karlkras** [paslandau/laravelexample#1]
One of your first instruction after clone says:

to prepare the vagrant configuration, run
vendor/bin/homestead make or vendor/bin/homestead.bat make on Windows

there is no such directory in your distribution.

**Comment by karlkras** [comment]
I wouldn't have filed this, but your instructions for the web article didn't work either.

**Comment by paslandau** [comment]
Hey @karlkras,
you need to run `composer install` upfront. That will create the `vendor` folder.

I just added that piece of information to the readme, thx for filing the bug.

Cheers
Pascal
